# "make clean" clears out all tmp and intermediate files.
clean:
	-rm *~
	for FILE in * ; do \
		if( test -d $$FILE ) ; then \
			if( test -e $$FILE/Makefile ) ; then \
				make -C $$FILE clean ; \
			fi; \
		fi; \
	done
