DROP   TABLE framework.countries;
CREATE TABLE framework.countries ( id   INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
                                  name CHAR(24) );
INSERT INTO framework.countries (name) VALUES ('Algeria');
INSERT INTO framework.countries (name) VALUES ('Antigua');
INSERT INTO framework.countries (name) VALUES ('Argentina');
INSERT INTO framework.countries (name) VALUES ('Australia');
INSERT INTO framework.countries (name) VALUES ('Austria');
INSERT INTO framework.countries (name) VALUES ('Bahamas');
INSERT INTO framework.countries (name) VALUES ('Bangladesh');
INSERT INTO framework.countries (name) VALUES ('Barbados');
INSERT INTO framework.countries (name) VALUES ('Belgium');
INSERT INTO framework.countries (name) VALUES ('Bermuda');
INSERT INTO framework.countries (name) VALUES ('Bolivia');
INSERT INTO framework.countries (name) VALUES ('Brazil');
INSERT INTO framework.countries (name) VALUES ('Bulgaria');
INSERT INTO framework.countries (name) VALUES ('Canada');
INSERT INTO framework.countries (name) VALUES ('Cayman Islands');
INSERT INTO framework.countries (name) VALUES ('Chile');
INSERT INTO framework.countries (name) VALUES ('China');
INSERT INTO framework.countries (name) VALUES ('Colombia');
INSERT INTO framework.countries (name) VALUES ('Costa Rica');
INSERT INTO framework.countries (name) VALUES ('Cuba');
INSERT INTO framework.countries (name) VALUES ('Cyprus');
INSERT INTO framework.countries (name) VALUES ('Czech Republic');
INSERT INTO framework.countries (name) VALUES ('Denmark');
INSERT INTO framework.countries (name) VALUES ('Dominican Republic');
INSERT INTO framework.countries (name) VALUES ('Ecuador');
INSERT INTO framework.countries (name) VALUES ('Egypt');
INSERT INTO framework.countries (name) VALUES ('El Salvador');
INSERT INTO framework.countries (name) VALUES ('England');
INSERT INTO framework.countries (name) VALUES ('Estonia');
INSERT INTO framework.countries (name) VALUES ('Ethiopia');
INSERT INTO framework.countries (name) VALUES ('Fiji');
INSERT INTO framework.countries (name) VALUES ('Finland');
INSERT INTO framework.countries (name) VALUES ('France');
INSERT INTO framework.countries (name) VALUES ('Germany');
INSERT INTO framework.countries (name) VALUES ('Ghana');
INSERT INTO framework.countries (name) VALUES ('Greece');
INSERT INTO framework.countries (name) VALUES ('Grenada');
INSERT INTO framework.countries (name) VALUES ('Guadaloupe');
INSERT INTO framework.countries (name) VALUES ('Guatemala');
INSERT INTO framework.countries (name) VALUES ('Guyana');
INSERT INTO framework.countries (name) VALUES ('Haiti');
INSERT INTO framework.countries (name) VALUES ('Honduras');
INSERT INTO framework.countries (name) VALUES ('Hong Kong');
INSERT INTO framework.countries (name) VALUES ('Hungary');
INSERT INTO framework.countries (name) VALUES ('Iceland');
INSERT INTO framework.countries (name) VALUES ('India');
INSERT INTO framework.countries (name) VALUES ('Indonesia');
INSERT INTO framework.countries (name) VALUES ('Iran');
INSERT INTO framework.countries (name) VALUES ('Iraq');
INSERT INTO framework.countries (name) VALUES ('Ireland');
INSERT INTO framework.countries (name) VALUES ('Israel');
INSERT INTO framework.countries (name) VALUES ('Italy');
INSERT INTO framework.countries (name) VALUES ('Jamaica');
INSERT INTO framework.countries (name) VALUES ('Japan');
INSERT INTO framework.countries (name) VALUES ('Jordan');
INSERT INTO framework.countries (name) VALUES ('Kenya');
INSERT INTO framework.countries (name) VALUES ('Korea');
INSERT INTO framework.countries (name) VALUES ('Kuwait');
INSERT INTO framework.countries (name) VALUES ('Latvia');
INSERT INTO framework.countries (name) VALUES ('Lebanon');
INSERT INTO framework.countries (name) VALUES ('Lesotho');
INSERT INTO framework.countries (name) VALUES ('Liechtenstein');
INSERT INTO framework.countries (name) VALUES ('Luxembourg');
INSERT INTO framework.countries (name) VALUES ('Malaysia');
INSERT INTO framework.countries (name) VALUES ('Malta');
INSERT INTO framework.countries (name) VALUES ('Martinique');
INSERT INTO framework.countries (name) VALUES ('Mauritius');
INSERT INTO framework.countries (name) VALUES ('Mexico');
INSERT INTO framework.countries (name) VALUES ('Monaco');
INSERT INTO framework.countries (name) VALUES ('Morocco');
INSERT INTO framework.countries (name) VALUES ('Namibia');
INSERT INTO framework.countries (name) VALUES ('Nepal');
INSERT INTO framework.countries (name) VALUES ('New Caledonia');
INSERT INTO framework.countries (name) VALUES ('New Zealand');
INSERT INTO framework.countries (name) VALUES ('Nicaragua');
INSERT INTO framework.countries (name) VALUES ('Nigeria');
INSERT INTO framework.countries (name) VALUES ('Norway');
INSERT INTO framework.countries (name) VALUES ('Oman');
INSERT INTO framework.countries (name) VALUES ('Pakistan');
INSERT INTO framework.countries (name) VALUES ('Panama');
INSERT INTO framework.countries (name) VALUES ('Paraguay');
INSERT INTO framework.countries (name) VALUES ('Peru');
INSERT INTO framework.countries (name) VALUES ('Philippines');
INSERT INTO framework.countries (name) VALUES ('Poland');
INSERT INTO framework.countries (name) VALUES ('Portugal');
INSERT INTO framework.countries (name) VALUES ('Puerto Rico');
INSERT INTO framework.countries (name) VALUES ('Qatar');
INSERT INTO framework.countries (name) VALUES ('Romania');
INSERT INTO framework.countries (name) VALUES ('Russia');
INSERT INTO framework.countries (name) VALUES ('Rwanda');
INSERT INTO framework.countries (name) VALUES ('Saint Martin');
INSERT INTO framework.countries (name) VALUES ('Salvador');
INSERT INTO framework.countries (name) VALUES ('Saudi Arabia');
INSERT INTO framework.countries (name) VALUES ('Singapore');
INSERT INTO framework.countries (name) VALUES ('Slovak Republic');
INSERT INTO framework.countries (name) VALUES ('Slovenia');
INSERT INTO framework.countries (name) VALUES ('South Africa');
INSERT INTO framework.countries (name) VALUES ('South Korea');
INSERT INTO framework.countries (name) VALUES ('Spain');
INSERT INTO framework.countries (name) VALUES ('Sri Lanka');
INSERT INTO framework.countries (name) VALUES ('Surinam');
INSERT INTO framework.countries (name) VALUES ('Swaziland');
INSERT INTO framework.countries (name) VALUES ('Sweden');
INSERT INTO framework.countries (name) VALUES ('Switzerland');
INSERT INTO framework.countries (name) VALUES ('Syria');
INSERT INTO framework.countries (name) VALUES ('Taiwan');
INSERT INTO framework.countries (name) VALUES ('Tanzania');
INSERT INTO framework.countries (name) VALUES ('Thailand');
INSERT INTO framework.countries (name) VALUES ('The Netherlands');
INSERT INTO framework.countries (name) VALUES ('Turkey');
INSERT INTO framework.countries (name) VALUES ('United Arab Emirates');
INSERT INTO framework.countries (name) VALUES ('United Kingdom');
INSERT INTO framework.countries (name) VALUES ('United States');
INSERT INTO framework.countries (name) VALUES ('Uruguay');
INSERT INTO framework.countries (name) VALUES ('Venezuela');
INSERT INTO framework.countries (name) VALUES ('Yemen');
INSERT INTO framework.countries (name) VALUES ('Yugoslavia');
INSERT INTO framework.countries (name) VALUES ('Zimbabwe');
